name: Publish
on: repository_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Finish release
        run: ./.scripts/ci/finish-release.sh "${{ github.event.client_payload.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          tags: true
          force: true
